#ifndef TRANSACTION_H
#define TRANSACTION_H

#include <string>

class Transaction {
public:
    Transaction() = default;
    Transaction(const std::string& sender,
                const std::string& recipient,
                double amt,
                const std::string& sig = std::string(),
                const std::string& data = std::string())
        : sender_addr(sender), recipient_addr(recipient), amount(amt), signature(sig), dataMsg(data) {}

    //accessors
    const std::string& getSender() const { return sender_addr; }
    const std::string& getRecipient() const { return recipient_addr; }
    double getAmount() const { return amount; }
    const std::string& getSignature() const { return signature; }
    const std::string& getDataMsg() const { return dataMsg; }

    std::string toString() const;
    bool isValid() const;

private:
    std::string sender_addr; 
    std::string recipient_addr;
    double amount{0.0};
    std::string signature; //will be generated by the sender's private key, and verified by the recipient's public key
    std::string dataMsg; //the message that will be signed by the sender's private key, and verified by the recipient's public key
};

#endif