#ifndef TRANSACTION_H
#define TRANSACTION_H

#include <string>

struct Transaction { //will change to a class later, for now we just use a struct to represent a transaction (maybe)
    std::string sender_addr; //the sender's public key, which will be used to verify the signature
    std::string recipient_addr; //the recipient's public key, which will be used to verify the signature
    double amount;
    //and a signature field later on, but for now we just want to get the basic functionality working
    std::string signature; //will be generated by the sender's private key, and verified by the recipient's public key

    std::string dataMsg; //the message that will be signed by the sender's private key, and verified by the recipient's public key

    //helper to turn the transaction into a string for hashing
    std::string toString() const;
    bool isValid() const;
};

#endif